version: '3.8'

services:

  mongodb:
    image: mongo:4.4.5
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    healthcheck:
      test: "echo 'db.stats().ok' | mongo localhost:27017/productdb --quiet"
      start_period: 30s

  postgres:
    image: postgres:13.2
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=customerdb
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    healthcheck:
      test: "pg_isready -U postgres"
      start_period: 10s

  cassandra:
    image: cassandra:3.11.10
    container_name: cassandra
    restart: unless-stopped
    ports:
      - "9042:9042"
      - "7199:7199"
      - "9160:9160"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      start_period: 30s
